#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:data", "data")

#@ def updates():
korifi_controller_namespace: #@ data.values.contour_tls_namespace
workloads_tls_secret_name: #@ "tas-adapter-{}".format(data.values.contour_tls_secret)
#@ end

#@overlay/match by=overlay.subset({"metadata":{"name":"korifi-controllers-config"}, "kind": "ConfigMap"})
---
data:
  #@overlay/replace via=lambda a,_: yaml.encode(overlay.apply(yaml.decode(a), updates()))
  korifi_controllers_config.yaml:
