#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"metadata":{"name":"korifi-api-proxy"}, "kind": "HTTPProxy"})
---
spec:
  virtualhost:
    tls:
      #@overlay/match missing_ok=True
      secretName: #@ "{}/{}".format(data.values.contour_tls_namespace,data.values.contour_tls_secret)
