---
apiVersion: v1
kind: Secret
metadata:
  name: cnrs-certmanager-config-overlay
  annotations:
    kapp.k14s.io/change-group: tap/package-overlays
stringData:
  cnrs-certmanager-config-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"metadata":{"name":"config-certmanager"}, "kind": "ConfigMap"})
    ---
    #@overlay/match missing_ok=True
    data:
      #@overlay/match missing_ok=True
      issuerRef: |
        kind: ClusterIssuer
        name: letsencrypt-contour-cluster-issuer
