#@ load("@ytt:assert", "assert")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")

#@ def app_registry_secret_name():
#@ return data.values.container_registry.secret_name or assert.fail("missing container_registry.secret_name")
#@ end

#@ def app_registry_username():
#@ return data.values.container_registry.username or assert.fail("missing container_registry.username")
#@ end

#@ def app_registry_password():
#@ return data.values.container_registry.password or assert.fail("missing container_registry.password")
#@ end

#@ def app_registry_hostname():
#@ return data.values.container_registry.hostname or assert.fail("missing container_registry.hostname")
#@ end

---
apiVersion: v1
kind: Secret
metadata:
  name: #@ app_registry_secret_name()
  namespace: tap-install
type: kubernetes.io/dockerconfigjson
data:
  #@ docker_auth = base64.encode("{}:{}".format(app_registry_username(), app_registry_password()))
  #@ docker_creds = {"username": app_registry_username(), "password": app_registry_password(), "auth": docker_auth}
  .dockerconfigjson: #@ base64.encode(json.encode({"auths": {app_registry_hostname(): docker_creds}}))
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: #@ app_registry_secret_name()
  namespace: tap-install
spec:
  toNamespace: cf
