#@ load("@ytt:data", "data")
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cf-admin
  namespace: cf
subjects:
- kind: User
  name: #@ data.values.admin.username
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: korifi-controllers-admin
  apiGroup: rbac.authorization.k8s.io
