#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  namespace: cert-manager
#@ if "aws" in data.values:
  name: prod-route53-credentials-secret
stringData:
  secret-access-key: #@ data.values.aws.credentials.secretKey
#@ elif "azure" in data.values:
  name: azure-dns-config
stringData:
  clientSecret: #@ data.values.azure.credentials.aad_client_secret
#@ end
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-contour-cluster-issuer
spec:
  acme:
    email: #@ data.values.acme.email
    privateKeySecretRef:
      name: acme-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
#@ if "aws" in data.values:
          route53:
            region: #@ data.values.aws.region
            hostedZoneID: #@ data.values.aws.route_fifty_three_zone_id
            accessKeyID: #@ data.values.aws.credentials.accessKey
            secretAccessKeySecretRef:
              name: prod-route53-credentials-secret
              key: secret-access-key
#@ elif "azure" in data.values:
          azureDNS:
            clientID: #@ data.values.azure.credentials.aad_client_id
            clientSecretSecretRef:
              name: azure-dns-config
              key: clientSecret
            subscriptionID: #@ data.values.azure.subscription_id
            tenantID: #@ data.values.azure.tenant_id
            resourceGroupName: #@ data.values.azure.resource_group
            hostedZoneName: #@ data.values.ingress.domain
            environment: AzurePublicCloud
#@ end
